//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ostateczny_WPF_projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminyUmowione
    {
        public int ID_TerminyUmowione { get; set; }
        public Nullable<int> ID_lekarza { get; set; }
        public Nullable<int> ID_pacjenta { get; set; }
        public Nullable<int> ID_termiu { get; set; }
    
        public virtual Lekarz Lekarz { get; set; }
        public virtual Pacjent Pacjent { get; set; }
        public virtual Terminy Terminy { get; set; }
    }
}
